import { getAllBookings, getCardsData } from "../../helpers/api-utils";
// import SmallCard from "../../components/SmallCard";
import MediumCard from "../../components/MediumCard";
import LargeCard from "../../components/LargeCard";
import Head from "next/head";
import Header from "../../components/Header";
import Banner from "../../components/Banner";
import Footer from "../../components/Footer";

export default function Index({ exploreData, cardsData }) {
  return (
    <div>
      <Head>
        <title>Booking App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <div className="">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          {/*<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">*/}
          {/*  /!*  pull data from server *!/*/}
          {/*  {exploreData?.map((item) => (*/}
          {/*    <SmallCard*/}
          {/*      img={item.img}*/}
          {/*      distance={item.distance}*/}
          {/*      location={item.location}*/}
          {/*      key={item.id}*/}
          {/*    />*/}
          {/*  ))}*/}
          {/*</div>*/}
        </section>

        <section>
          <h2 className="text-4xl font-semibold py-8">Travel Anywhere</h2>
          {/*<div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">*/}
          {/*  {cardsData?.map((item) => (*/}
          {/*    <MediumCard key={item.id} img={item.img} title={item.title} />*/}
          {/*  ))}*/}
          {/*</div>*/}
        </section>

        {/*<LargeCard*/}
        {/*  img="/travel-bus.jpg"*/}
        {/*  title="Greatest booking app"*/}
        {/*  description="Get your booking done, the easy way"*/}
        {/*  buttonText="Start your journey"*/}
        {/*  layout="fill"*/}
        {/*/>*/}
      </div>
      <Footer />
    </div>
  );
}

export async function getServerSideProps() {
  const exploreData = await getAllBookings();
  const cardsData = await getCardsData();
  return {
    props: {
      exploreData: exploreData,
      cardsData: cardsData, // for clarity only, can shorten to just exploreData
    },
  };
}
